networks:
  proxy:
    external: true

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    labels:
      - traefik.enable=true
      - traefik.http.routers.homeassistant-https.entrypoints=websecure
      - traefik.http.routers.homeassistant-https.rule=Host(`${SUB_DOMAIN}.${DOMAIN}`)
      - traefik.http.routers.homeassistant-https.tls=true
      - traefik.http.routers.homeassistant-https.tls.certresolver=tls
      - traefik.http.routers.homeassistant-https.service=homeassistant
      - traefik.http.services.homeassistant.loadbalancer.server.port=8123
    networks:
      - proxy
    # network_mode: host
