version: "3.9"

volumes:
  nextcloud:


networks:
  database:
    external: true
  proxy:
    external: true

services:
  nextcloud:
    image: nextcloud:latest
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud-https.entrypoints=websecure
      - traefik.http.routers.nextcloud-https.rule=Host(`${SUB_DOMAIN}.${DOMAIN}`)
      - traefik.http.routers.nextcloud-https.tls=true
      - traefik.http.routers.nextcloud-https.tls.certresolver=tls
      - traefik.http.routers.nextcloud-https.service=nextcloud
      - traefik.http.services.nextcloud.loadbalancer.server.port=80
      # - com.centurylinklabs.watchtower.enable=true
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - proxy
      - database
