# https://community.traefik.io/t/setting-up-traefik-for-docker-and-external-services/14151
http:
  routers:
    proxmox:
      entryPoints:
        - "web"
        - "websecure"
      rule: Host(`proxmox.danielricklin.fr`)
      middlewares:
        - https-redirect
        - default-headers
      tls:
        certResolver: tls
      service: proxmox

  services:
    proxmox:
      loadBalancer:
        servers:
          - url: "https://10.1.192.2:8006"
          # - url: "https://192.168.1.250:8006"
        passHostHeader: true
  
  middlewares:    
    crowdsec-bouncer:
      forwardauth:
        address: http://bouncer-traefik:8080/api/v1/forwardAuth
        trustForwardHeader: true
    ipwhitelist:
      ipWhiteList:
        sourceRange:
          - "127.0.0.1/32"
          - "192.168.1.0/24"
        ipStrategy:
          depth: 0
    basic-auth:
      basicAuth:
        users: "{{ env "AUTHDASH"}}"
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https