# https://community.traefik.io/t/setting-up-traefik-for-docker-and-external-services/14151
http:
  middlewares:    
    crowdsec-bouncer:
      forwardauth:
        address: http://bouncer-traefik:8080/api/v1/forwardAuth
        trustForwardHeader: true