global:
  checkNewVersion: false
  sendAnonymousUsage: false
entryPoints:
  web:
    address: :80
    http:
      middlewares:
        - crowdsec-bouncer@file
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
    http:
      tls: true
      middlewares:
        - crowdsec-bouncer@file
certificatesResolvers:
  tls:
    acme:
      email: ${EMAIL_ADDRESS}
      storage: /etc/traefik/acme.json
      # caServer: 'https://acme-staging-v02.api.letsencrypt.org/directory'
      keyType: "RSA4096"
      caServer: 'https://acme-v02.api.letsencrypt.org/directory'
      dnsChallenge:
        provider: ovh
      httpChallenge:
        entryPoint: web
log:
  level: INFO
  filepath: /var/log/traefik/traefik.log
accesslog:
  # format: json  # common, json, logfmt
  filePath: /var/log/traefik/access.log
api:
  insecure: false
  dashboard: true
  debug: true
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    exposedByDefault: false
    endpoint: 'unix:///var/run/docker.sock'
    watch: true
    swarmMode: false
    network: proxy
  file:
    filename: "/etc/traefik/dynamic-config.yml"
    watch: true