global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
    http:
      tls: true

certificatesResolvers:
  tls:
    acme:
      email: ricklin.daniel@outlook.fr
      storage: /etc/traefik/acme.json
      # caServer: 'https://acme-staging-v02.api.letsencrypt.org/directory'
      keyType: "RSA4096"
      caServer: 'https://acme-v02.api.letsencrypt.org/directory'
      dnsChallenge:
        provider: ovh
      httpChallenge:
        entryPoint: web

log:
  level: DEBUG

api:
  # insecure: true
  dashboard: true
  debug: true

providers:
  docker:
    exposedByDefault: false
    endpoint: 'unix:///var/run/docker.sock'
    watch: true
    swarmMode: false
    network: traefik
    # defaultRule: "Host(`{{ lower (trimPrefix `/` .Name )}}.danielricklin.fr`)" 
  file:
    filename: "/etc/traefik/tls.yml"
    watch: true