version: '3'
services:
  adguardhome:
    image: adguard/adguardhome
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 853:853/tcp
      - 853:853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
      - 6060:6060/tcp
    networks:
      traefik:
    volumes:
      - /data:/opt/adguardhome/work
      - /config:/opt/adguardhome/conf
    container_name: adguard
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.rule=Host(`adguard.danielricklin.fr`)"
      - "traefik.http.routers.adguard.tls=true"
      - "traefik.http.routers.adguard.entrypoints=https"
      - "traefik.http.services.adguard.loadbalancer.server.port=3000"