version: '3'
volumes:
  data:
services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    labels: # - com.centurylinklabs.watchtower.enable=true
    networks:
      - database
