version: '3'

networks:
  proxy:
    external: true

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    # ports:
    #   - "3010:3001"
    labels:
      - traefik.enable=true
      - traefik.http.routers.uk-https.entrypoints=websecure
      - traefik.http.routers.uk-https.rule=Host(`${SUB_DOMAIN}.${DOMAIN}`)
      - traefik.http.routers.uk-https.tls=true
      - traefik.http.routers.uk-https.tls.certresolver=tls
      - traefik.http.routers.uk-https.service=uk
      - traefik.http.services.uk.loadbalancer.server.port=3001
    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy

volumes:
  uptime-kuma:
